### ISSUE TITLE
Define the testable MVP

### ISSUE THREAD

**Issue by crisdb** [codefordenver/Wildlands-Defense#10]
### Define a testable Minimum Viable Product

An MVP is the smallest possible increment of your solution that delivers enough value for you to be able to ship it and learn from customers as quickly as possible.
- [x] Agree as a team: from your paper prototype and lean canvas, what's the riskiest assumption you're making?

For example, if you were building a device that would automatically pour beer for you, the riskiest assumption might be technical - how do you know how much volume of beer to pour? If you were building AirBnB, the riskiest assumption wouldn't be tech, but instead would be trust - will users rent out a bedroom in their house to a stranger?
- [x] Take your riskiest assumption and figure out the smallest increment you need to build to test that assumption.
- [x] Take that increment and create cards on your board to represent what your team needs to get done in the next Sprint to build that iteration. Think about what it will take to test your MVP - it's not just about building something, it's about building something you can use to learn from _as fast as possible_.

This backlog of work can be used in your pitch too, to answer "What's next?"

![MVP](https://pbs.twimg.com/media/BzUBDdhCEAAdmsp.jpg)

**Comment by crisdb** [comment]
Donavan.... (for two weeks from now)

**Comment by crisdb** [comment]
We have wireframes!

**Comment by crisdb** [comment]
I think we all need to work on this one together.

**Comment by dmille56** [comment]
[mvp_5-5-16.txt](https://github.com/codefordenver/Wildlands-Defense/files/285778/mvp_5-5-16.txt)

**Comment by roballsopp** [comment]
I wonder if we would even need login functionality for MVP. We probably want this to be as simple and quick to use as possible, and it doesn't seem like we really care about user data, so much as tagged and geolocated photos. We could literally just let anyone with the app upload stuff without any sort of login and probably have the real core of what we are after

**Comment by crisdb** [comment]
Thanks guys.. I think this is good for MVP: 
file browser for photo
description for photo: type of animal, date, GPS data
threat level selector
-database
-server
