### ISSUE TITLE
Java Services

### ISSUE THREAD

**Issue by abw1914** [codefordenver/Wildlands-Defense#14]

**Comment by crisdb** [comment]
We still need an API.. we need two repositories...

**Comment by crisdb** [comment]
there is a java sdk for AWS, we are gonna use AWS, you may want to look at it. As a fall back we have Node.

**Comment by abw1914** [comment]
I can not find a java api for a javascript based web app.  I'll check again with Donovan and others but I can't find anything.  I think the solutions is php based on youtube.
